AGENT_GROUP: 
    n_agents: 1000
    p_lambda: 0.5
    ng_r: 10
    ng_p: 0.17
    b_p: 0.5
    max_delta: 50
    seed: 1337
  

ORDER_BOOK:
  tick_size: 0.50
  starting_price: 100.00

SIMULATOR:
  n_steps: 5_000_000

  